#162163165 Users should receive descriptive signup/Registration validation errors
andela/ah-backend-zeus pull request #10
Opened 2018-12-04 15:37 UTC by barema4

### What does this PR do?
It adds validations and meaningful validation error messages to signup
### Description of Task to be completed

- Creating validations.py file 
- Writing tests for signup with validations

### How should this be manually tested?

- Install project requirements from pip install -r requirements.txt
- Run the server and try to input signup credentials
### What are the relevant pivotal tracker stories?
[#162163165 ](https://www.pivotaltracker.com/story/show/162163165)

2018-12-04 15:47 UTC, ekumamait requested changes
Sam kindly add a tag to the Pull Request.

2018-12-05 06:07 UTC, alexkayabula approved these changes
Good work

2018-12-05 06:10 UTC, sekayasin reviewed
@barema4 Looks good! Just check on the variable naming.

2018-12-05 06:11 UTC, sekayasin approved these changes

2018-12-05 09:49 UTC, lindseyme approved these changes

2018-12-05 11:57 UTC, ekumamait approved these changes

2018-12-05 13:21 UTC, mulondo approved these changes

2018-12-06 13:52 UTC, merged